owner: estiimate
repo: upptime

sites:
  - name: Web
    url: https://estii.com
  - name: App
    url: https://app.estii.com
  - name: API
    url: https://api.estii.com

status-website:
  cname: status.estii.com
  logoUrl: https://app.estii.com/favicon.svg
  name: Estii Service Status
  introTitle: "Uptime and response times for Estii Services"
  introMessage: "Please email support@estii.com if the information on this page is inaccurate!"
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://estii.com
    - title: App
      href: https://app.estii.com
    - title: Docs
      href: https://docs.estii.com
